version: '2'

services:
  db:
    image: postgres:latest
    env_file:
      - db.env
    ports:
        - "5432:5432"
    volumes:
      - /home/ubuntu/data/db:/var/lib/postgresql/data

  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python /code/manage.py runserver 0.0.0.0:8000"
    environment:
      - PYTHONPATH=/code/
    ports:
      - "8000:8000"
    env_file:
      - db.env
    depends_on:
      - db
